version: '3.8'

services:
  traefik:
    build:
      context: .
      dockerfile: Dockerfile 
      target: traefik
    command:
      - '--api.dashboard=true'
      - '--entryPoints.web.address=:80'
      - '--providers.docker'
    ports:
      - '80:80'
    security_opt:
      - no-new-privileges:true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.localhost`)'
      - 'traefik.http.routers.traefik.service=api@internal'
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nginx.rule=Host(`front.localhost`) &&
        PathPrefix(`/images`)'
    restart: unless-stopped
   
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: node
    volumes:
      - './src:/app/src'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app.rule=Host(`front.localhost`)'
      - 'traefik.http.routers.app.entrypoints=web'
      - 'traefik.http.services.app.loadbalancer.server.port=3000'
    restart: unless-stopped
